Repository argoproj/argo-rollouts, pull requests merged in 2022-11, with the labels that each got.

#2345 chore(deps): upgrade ui deps to fix high security cve's
  ui/package.json
  ui/src/app/components/pods/pods.tsx
  ui/yarn.lock
Labels: ready-for-review

#2386 chore: add getyourguide to users
  USERS.md
Labels: ready-for-review

#2372 docs: fix !important block typo
  docs/features/ephemeral-metadata.md
  docs/features/traffic-management/alb.md
Labels: hacktoberfest-accepted, ready-for-review

#2315 chore: rename the examples/trafffic-routing directory to istio
  examples/istio/istio-mirror.yaml
Labels: ready-for-review

#2383 feat(cli): add port flag for dashboard command. Fixes #2382
  pkg/kubectl-argo-rollouts/cmd/dashboard/dashboard.go
Labels: ready-for-review

#2303 fix(dashboard): correct mime type is returned. Fixes: #2290
  server/server.go
  server/server_static.go
  server/server_static_test.go
  server/static_test/index.html
  server/static_test/test-dir/test.css
Labels: hacktoberfest-accepted, ready-for-review

#2352 docs: update examples to remove deprecated APIs in k8s 1.25
  examples/notifications/rollout-canary.yaml
  examples/traffic-routing-experiment-step/rollout-alb-experiment-step.yaml
  examples/traffic-routing-experiment-step/rollout-smi-experiment-step.yaml
Labels: hacktoberfest-accepted, ready-for-review

#2378 docs: add deprecation notice for rollout_phase in docs (#2377)
  docs/features/controller-metrics.md
Labels: ready-for-review

#2309 fix(example): correct docs when metrics got result empty
  docs/features/analysis.md
Labels: docs, ready-for-review

#2300 feat(controller): Add prometheus metric for updatedReplicas. Fixes #2297
  controller/metrics/prommetrics.go
  controller/metrics/rollout_test.go
  controller/metrics/rollouts.go
  docs/features/controller-metrics.md
Labels: hacktoberfest-accepted, ready-for-review

#2394 feat: rollback windows. Fixes #574
  .github/workflows/go.yml
  docs/features/specification.md
  docs/rollback.md
  manifests/crds/rollout-crd.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
  mkdocs.yml
  pkg/apiclient/rollout/rollout.swagger.json
  pkg/apis/rollouts/v1alpha1/generated.pb.go
  pkg/apis/rollouts/v1alpha1/generated.proto
  pkg/apis/rollouts/v1alpha1/openapi_generated.go
  pkg/apis/rollouts/v1alpha1/types.go
  pkg/apis/rollouts/v1alpha1/zz_generated.deepcopy.go
  rollout/bluegreen.go
  rollout/canary.go
  rollout/sync.go
  rollout/sync_test.go
  test/e2e/functional/analysistemplate-sleep-job.yaml
  test/e2e/functional/rollout-rollback-window.yaml
  test/e2e/rollback_window_test.go
  ui/src/models/rollout/generated/api.ts
Labels: ready-for-review

#2438 chore: Rename docs/rollback.md to docs/features/rollback.md
  docs/features/rollback.md
Labels: docs

#2440 fix: dev build can set DEV_IMAGE=true
  Makefile
Labels: bug
