Repository argoproj/argo-rollouts, pull requests merged in 2022-09, with the labels that each got.

#2216 docs: Update docs for new openapi kustomize support
  docs/features/kustomize.md
  test/kustomize/rollout/kustomization.yaml
Labels: ready-for-review

#2214 feat: Allow Traffic shaping through header based routing for ALB
  ingress/alb.go
  ingress/alb_test.go
  pkg/apis/rollouts/validation/validation.go
  pkg/apis/rollouts/validation/validation_test.go
  rollout/trafficrouting/alb/alb.go
  rollout/trafficrouting/alb/alb_test.go
  test/e2e/aws_test.go
  test/e2e/header-routing/alb-header-route.yaml
  utils/defaults/defaults.go
  utils/defaults/defaults_test.go
  utils/ingress/ingress.go
  utils/ingress/ingress_test.go
  utils/ingress/wrapper.go
  utils/ingress/wrapper_test.go
Labels: ready-for-review

#2231 fix: enable notifications without when condition
  utils/record/record.go
  utils/record/record_test.go
Labels: bug, cherry-pick/release-1.3

#2244 chore(cli): Use standard cli format for dashboard root path
  pkg/kubectl-argo-rollouts/cmd/dashboard/dashboard.go
  server/server.go
Labels: cherry-pick/release-1.3

#2245 docs: Update release docs for versioned formula
  docs/releasing.md
Labels: docs, ready-for-review

#2238 docs: Fix the controller annotation to enable data scrapping
  docs/features/controller-metrics.md
Labels: ready-for-review

#2230 fix(analysis): Make AnalysisRun end when only Dry-Run metrics are defined. Fixes: #2151
  analysis/analysis.go
  analysis/analysis_test.go
Labels: analysis

#2209 docs: add OpsVerse as an official user (USERS.md)
  USERS.md
Labels: ready-for-review

#2027 docs: common questions for Rollbacks
  docs/FAQ.md
Labels: ready-for-review

#2183 chore imports: remove repeated package and reformat imports
  cmd/rollouts-controller/main.go
  controller/controller.go
Labels: ready-for-review

#2261 fix(controller): Fix k8s clientset controller metrics. Fixes #2139
  USERS.md
  cmd/rollouts-controller/main.go
  controller/metrics/client.go
Labels: ready-for-review, cherry-pick/release-1.3

#2264 chore(cli): add darwin arm64 to build and release
  .github/workflows/release.yaml
  Makefile
  hack/build-release-plugins.sh
Labels: ready-for-review

#2256 fix: nil pointer while linting with basic canary and ingresses
  pkg/kubectl-argo-rollouts/cmd/lint/lint.go
  pkg/kubectl-argo-rollouts/cmd/lint/lint_test.go
  pkg/kubectl-argo-rollouts/cmd/lint/testdata/valid-nginx-basic-canary.yml
Labels: ready-for-review, cherry-pick/release-1.3

#2268 fixes(controller): istio dropping fields not defined in type
  rollout/trafficrouting/istio/istio.go
  rollout/trafficrouting/istio/istio_test.go
  rollout/trafficrouting/istio/istio_types.go
Labels: ready-for-review, cherry-pick/release-1.3
