Repository argoproj/argo-rollouts, pull requests merged in 2023-05, with the labels that each got.

#2689 fix(controller): Fix for rollouts getting stuck in loop
  rollout/controller.go
Labels: cherry-pick/release-1.3, cherry-pick/release-1.4, cherry-pick/release-1.5

#2692 fix: istio dropping fields during removing of managed routes
  rollout/trafficrouting/istio/istio.go
  rollout/trafficrouting/istio/istio_test.go
Labels: cherry-pick/release-1.3, cherry-pick/release-1.4, cherry-pick/release-1.5

#2775 fix: properly wrap Datadog API v2 request body (#2771)
  metricproviders/datadog/datadog.go
  metricproviders/datadog/datadogV2_test.go
Labels: ready-for-review, cherry-pick/release-1.5

#2783 ci: use keyless signing for main and release branches
  .github/workflows/docker-publish.yml
  .github/workflows/image-reuse.yaml
Labels: cherry-pick/release-1.3, cherry-pick/release-1.4, cherry-pick/release-1.5

#2806 fix: make new alb fullName field optional for backward compatability
  manifests/crds/rollout-crd.yaml
  manifests/install.yaml
  pkg/apiclient/rollout/rollout.swagger.json
  pkg/apis/rollouts/v1alpha1/generated.proto
  pkg/apis/rollouts/v1alpha1/openapi_generated.go
  pkg/apis/rollouts/v1alpha1/types.go
Labels: cherry-pick/release-1.5
