Repository argoproj/argo-rollouts, pull requests merged in 2023-10, with the labels that each got.

#3060 fix: inopportune scaling events would lose some status fields
  rollout/sync.go
Labels: cherry-pick/release-1.4, cherry-pick/release-1.5, cherry-pick/release-1.6

#3075 fix: sync notification controller configmaps/secrets first
  controller/controller.go
Labels: cherry-pick/release-1.6

#3076 fix: missing notification on error
  utils/record/record.go
  utils/record/record_test.go
Labels: cherry-pick/release-1.6

#3095 fix: bump notification-engine to fix double send on self server notifications
  docs/generated/notification-services/awssqs.md
  docs/generated/notification-services/github.md
  docs/generated/notification-services/googlechat.md
  docs/generated/notification-services/grafana.md
  docs/generated/notification-services/overview.md
  docs/generated/notification-services/slack.md
  go.mod
  go.sum
  mkdocs.yml
Labels: cherry-pick/release-1.6

#3077 fix: rollback to stable with dynamicStableScale could overwhelm stable pods
  rollout/bluegreen.go
  rollout/canary.go
  rollout/canary_test.go
  rollout/replicaset.go
  rollout/replicaset_test.go
  rollout/service.go
  rollout/service_test.go
  rollout/trafficrouting.go
  rollout/trafficrouting_test.go
  test/e2e/canary_test.go
  test/fixtures/common.go
  test/fixtures/when.go
  utils/replicaset/canary.go
  utils/replicaset/replicaset.go
  utils/replicaset/replicaset_test.go
Labels: cherry-pick/release-1.4, cherry-pick/release-1.5, cherry-pick/release-1.6

#3133 fix: docs require build.os to be defined
  .readthedocs.yaml
Labels: cherry-pick/release-1.2, cherry-pick/release-1.3, cherry-pick/release-1.4, cherry-pick/release-1.5, cherry-pick/release-1.6
