Repository argoproj/argo-rollouts, pull requests merged in 2023-04, with the labels that each got.

#1867 docs: update contributions.md to include k3d as recommended cluster, add details on e2e test setup, and update kubectl install link. Fixes #1750
  docs/CONTRIBUTING.md
Labels: no-pr-activity

#2701 fix(controller): Add klog logrus bridge. Fixes #2707.
  cmd/kubectl-argo-rollouts/main.go
  cmd/rollouts-controller/main.go
  go.mod
  go.sum
  utils/log/log.go
  utils/log/log_test.go
Labels: cherry-pick/release-1.3, cherry-pick/release-1.4, cherry-pick/release-1.5

#2719 docs: fix link to plugins for traffic routers
  mkdocs.yml
Labels: cherry-pick/release-1.5

#2731 docs: copy argo cd docs drop down fix
  docs/assets/versions.js
Labels: cherry-pick/release-1.2, cherry-pick/release-1.3, cherry-pick/release-1.4, cherry-pick/release-1.5

#2695 fix: change logic of analysis run to better handle errors
  analysis/analysis.go
  analysis/controller_test.go
Labels: cherry-pick/release-1.3, cherry-pick/release-1.4, cherry-pick/release-1.5

#2712 chore: bump k8s deps to v0.25.8
  docs/features/kustomize/rollout_cr_schema.json
  go.mod
  go.sum
  manifests/crds/analysis-run-crd.yaml
  manifests/crds/analysis-template-crd.yaml
  manifests/crds/cluster-analysis-template-crd.yaml
  manifests/crds/experiment-crd.yaml
  manifests/crds/rollout-crd.yaml
  manifests/install.yaml
  pkg/apiclient/rollout/rollout.swagger.json
  rollout/trafficrouting/apisix/mocks/apisix.go
  rollout/trafficrouting/traefik/mocks/traefik.go
  ui/src/models/rollout/generated/api.ts
Labels: cherry-pick/release-1.5
