Repository argoproj/argo-rollouts, pull requests merged in 2024-12, with the labels that each got.

#3968 fix(dashboard): No redirect loop when running on root. Fixes #3967
  server/server_static.go
  server/server_static_test.go
Labels: dashboard

#3960 docs: add descriptions for additional default trigger templates
  docs/features/notifications.md
Labels: docs

#3970 feat(analysis): Add ConsecutiveSuccessLimit feature to Analysis
  analysis/analysis.go
  analysis/analysis_test.go
  docs/features/kustomize/rollout_cr_schema.json
  manifests/crds/analysis-run-crd.yaml
  manifests/crds/analysis-template-crd.yaml
  manifests/crds/cluster-analysis-template-crd.yaml
  manifests/install.yaml
  pkg/apiclient/rollout/rollout.swagger.json
  pkg/apis/rollouts/v1alpha1/analysis_types.go
  pkg/apis/rollouts/v1alpha1/generated.pb.go
  pkg/apis/rollouts/v1alpha1/generated.proto
  pkg/apis/rollouts/v1alpha1/openapi_generated.go
  pkg/apis/rollouts/v1alpha1/zz_generated.deepcopy.go
  ui/src/app/components/analysis-modal/constants.ts
  ui/src/app/components/analysis-modal/criteria-list/criteria-list.tsx
  ui/src/app/components/analysis-modal/panels/metric-panel.tsx
  ui/src/models/rollout/generated/api.ts
  utils/analysis/factory.go
  utils/analysis/factory_test.go
Labels: analysis

#3987 chore(deps): update golang to 1.23
  .github/workflows/docker-publish.yml
  .github/workflows/gh-pages.yaml
  .github/workflows/go.yml
  .github/workflows/release.yaml
  .github/workflows/testing.yaml
  Dockerfile
  go.mod
Labels: dependencies, go

#3858 ci: add testing for k8s 1.30 and 1.31
  .github/workflows/testing.yaml
Labels: cherry-pick/release-1.8

#4005 fix: don't over reconcile on error
  rollout/controller.go
Labels: cherry-pick/release-1.8

#4012 docs: new syntax for docs conf
  .readthedocs.yaml
Labels: docs
