Repository argoproj/argo-rollouts, pull requests merged in 2024-06, with the labels that each got.

#3559 fix: rs conflict with fallback to patch
  .codecov.yml
  .github/workflows/e2e.yaml
  Makefile
  hack/gen-crd-spec/main.go
  rollout/canary.go
  rollout/canary_test.go
  rollout/controller.go
  rollout/controller_test.go
  rollout/ephemeralmetadata.go
  rollout/sync.go
  test/e2e/aws_test.go
  test/e2e/canary_test.go
  test/e2e/functional/analysistemplate-sleep-job.yaml
  test/e2e/functional_test.go
  test/fixtures/e2e_suite.go
  utils/annotations/annotations.go
  utils/controller/controller.go
  utils/replicaset/canary.go
Labels: cherry-pick/release-1.6, cherry-pick/release-1.7

#3627 fix: verify the weight of the alb at the end of the rollout
  rollout/trafficrouting.go
  rollout/trafficrouting/alb/alb.go
  rollout/trafficrouting/alb/alb_test.go
  rollout/trafficrouting_test.go
  utils/rollout/rolloututil.go
  utils/rollout/rolloututil_test.go
Labels: cherry-pick/release-1.6, cherry-pick/release-1.7

#3628 fix: when Rollout has pingpong and stable/canary service defined, only alb traffic management uses pingpong.
  rollout/canary.go
  rollout/service.go
  rollout/trafficrouting/alb/alb.go
  rollout/trafficrouting/istio/istio.go
  rollout/trafficrouting/service_helper.go
  rollout/trafficrouting/service_helper_test.go
  test/e2e/aws_test.go
  test/e2e/functional/albmesh-pingpong-stablecanary-rollout.yaml
Labels: cherry-pick/release-1.7

#3546 fix: Add volume for plugin and tmp folder
  manifests/base/argo-rollouts-deployment.yaml
  manifests/install.yaml
  manifests/namespace-install.yaml
Labels: cherry-pick/release-1.7

#3590 fix: docs site version selector broken
  docs/assets/versions.js
Labels: docs, cherry-pick/release-1.5, cherry-pick/release-1.6, cherry-pick/release-1.7

#3675 fix: add update verb to ClusterRole permissions for scaleDown feature. Fixes #3672
  manifests/install.yaml
  manifests/namespace-install.yaml
  manifests/role/argo-rollouts-clusterrole.yaml
Labels: cherry-pick/release-1.7

#3670 fix(analysis): Take RollbackWindow into account when Reconciling Analysis Runs. Fixes #3669
  rollout/analysis.go
  rollout/analysis_test.go
Labels: cherry-pick/release-1.7
